# Generated by Django 4.2.3 on 2023-07-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_color_car_purchaser_alter_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anycar', models.CharField(max_length=255)),
            ],
        ),
    ]
