# Generated by Django 4.2.3 on 2023-07-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='anycar',
            new_name='any_comment',
        ),
    ]
